jobs:
  find_duplicated_packages:
    name: Find Duplicated Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo check:packages
    timeout-minutes: 15

  lint-css:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:css
    timeout-minutes: 15

  lint-eslint:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:eslint
    timeout-minutes: 15

  lint-knip:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:knip
    timeout-minutes: 15

  lint-md:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint MD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:md
    timeout-minutes: 15

  lint-prettier:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:prettier
    timeout-minutes: 15

  lint-spelling:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:spelling
    timeout-minutes: 15

  lint-types:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: ðŸ”¬ Lint Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/pnpm-install
      - run: pnpm turbo lint:types
    timeout-minutes: 15

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
